import {
  FileText,
  ImageIcon,
  Scissors,
  RotateCw,
  Minimize2,
  Layers,
  QrCode,
  Maximize2,
  Crop as CropIcon,
  RefreshCw,
  FlipHorizontal,
  Palette,
  ShieldAlert,
  GripVertical,
  FileOutput,
  FileImage,
  Stamp,
  FileMinus,
  Unlock,
  Type,
  ImageDown,
  LayoutGrid,
  PenTool,
  ScanText,
  Combine,
  FileSearch
} from "lucide-react";

export const TOOLS_CONFIG = [
  // ==========================================
  // PDF TOOLS
  // ==========================================
  {
    id: "compress-pdf",
    type: "pdf",
    title: "Compress PDF",
    desc: "Reduce PDF file size efficiently without losing quality.",
    leadIn: "Shrink a heavy PDF to an exact size — 100 KB, 200 KB, or whatever an upload form demands — without turning your text to mush. Pick Best compression for everyday files, or Target size when a portal enforces a hard limit. Everything runs on your device, so bank statements and Aadhaar scans never leave your browser.",
    icon: Minimize2,
    color: "orange",
    config: { mode: "compress", accept: ".pdf" },
  },
  {
    id: "merge-pdf",
    type: "pdf",
    title: "Merge PDF",
    desc: "Combine multiple PDFs into one unified document.",
    leadIn: "Combine several PDFs — chapters, marksheets, invoices, scanned pages — into one clean file, in the order you choose. Drag the files to reorder, mix A4 with Letter or portrait with landscape, and download a single document. The files are stitched together inside your browser, not on a server.",
    icon: Layers,
    color: "orange",
    config: { mode: "merge", accept: ".pdf", allowBatch: true },
  },
  {
    id: "extract-pdf-pages",
    type: "pdf",
    title: "Extract PDF Pages",
    desc: "Extract specific pages or a range of pages from any large PDF document securely.",
    leadIn: "Pull the exact pages you need out of a big PDF — one page from a 500-page merit list, a signature page from a contract, the latest report from a heavy medical file. Select a continuous range or hand-pick scattered pages, then download them as a fresh document. The extraction runs in your browser, so the original stays on your device.",
    icon: FileOutput,
    color: "blue",
    config: { mode: "extract", accept: ".pdf" },
  },
  {
    id: "split-pdf",
    type: "pdf",
    title: "Split PDF",
    desc: "Extract pages from a PDF or split into multiple files.",
    leadIn: "Break one large PDF into smaller files — split by a page range, or pull out just the pages you need. Handy when an email limit rejects a heavy report, or when you want to share a few pages instead of the whole document. The original never leaves your device.",
    icon: Scissors,
    color: "orange",
    config: { mode: "split", accept: ".pdf" },
  },
  {
    id: "rotate-pdf",
    type: "pdf",
    title: "Rotate PDF",
    desc: "Rotate PDF pages permanently.",
    leadIn: "Fix a PDF that opens sideways or upside down — and have the rotation actually stay saved. Most viewers only turn the page on screen and forget it the moment you reopen the file; this rewrites the pages so the fix is permanent. Rotate the whole document or just the pages that are wrong, all on your own device.",
    icon: RotateCw,
    color: "orange",
    config: { mode: "rotate", accept: ".pdf" },
  },
  {
    id: "page-numbers",
    type: "pdf",
    title: "Page Numbers",
    desc: "Add page numbers to PDF documents.",
    leadIn: "Add clean, professional page numbers to any PDF — a thesis, a contract, a merged report. The tool counts the pages for you and lets you choose where the number sits and how it is styled, with safe margins so nothing overlaps your content. Everything is added inside your browser, so the file is never uploaded.",
    icon: FileText,
    color: "orange",
    config: { mode: "page-numbers", accept: ".pdf" },
  },
  {
    id: "image-to-pdf",
    type: "pdf",
    title: "Image to PDF",
    desc: "Convert JPG, PNG, and WebP images to PDF.",
    leadIn: "Turn photos and scans into a single, correctly sized PDF — ideal for assignments, ID copies, or receipts shot on a phone. Add multiple images, choose the page size (A4, Letter, or fit-to-image), and reorder them before exporting. The conversion happens on your device, so your pictures are never uploaded.",
    icon: ImageIcon,
    color: "orange",
    config: { mode: "image-to-pdf", accept: "image/*", allowBatch: true },
  },
  {
    id: "rearrange-pdf",
    type: "pdf",
    title: "Rearrange PDF",
    desc: "Change the page order of your PDF document easily with a visual editor.",
    leadIn: "Reorder the pages of a PDF by dragging them into place — move an executive summary to the front, or pull a stray page out of the middle. You see every page as a thumbnail and set the exact sequence you want, then export one clean file. The reordering happens in your browser, with no upload and no quality loss.",
    icon: GripVertical,
    color: "orange",
    config: { mode: "rearrange", accept: ".pdf", allowBatch: false },
  },

  {
    id: "pdf-to-image",
    type: "pdf",
    title: "PDF to JPG",
    desc: "Convert each PDF page into a high-quality JPG or PNG image.",
    leadIn: "Turn PDF pages into images — all of them, or just the ones you pick. Handy when a portal only accepts JPG, you want to share a single page on WhatsApp, or you need a page for a slide. Choose JPG for small, share-friendly files or PNG for lossless quality. It runs on your device, so the document is never uploaded.",
    icon: FileImage,
    color: "blue",
    config: { mode: "pdf-to-image", accept: ".pdf" },
  },
  {
    id: "watermark-pdf",
    type: "pdf",
    title: "Watermark PDF",
    desc: "Stamp text like CONFIDENTIAL or your name across every PDF page.",
    leadIn: "Stamp text like CONFIDENTIAL, DRAFT, or your name across every page of a PDF. Pick the position — diagonal, tiled, footer, or centre — and set the size, colour, and opacity so the mark stays visible without hiding the content. A live preview shows the result as you type, and the stamping happens entirely in your browser.",
    icon: Stamp,
    color: "blue",
    config: { mode: "watermark", accept: ".pdf" },
  },
  {
    id: "delete-pdf-pages",
    type: "pdf",
    title: "Delete PDF Pages",
    desc: "Remove unwanted, blank, or extra pages from a PDF in seconds.",
    leadIn: "Remove the pages you do not want from a PDF — a blank sheet at the end of a scan, instruction pages on a form, a duplicate. Just tap the pages to delete and download a clean, trimmed document. The pages you keep stay lossless, and the whole thing happens in your browser with nothing sent to a server.",
    icon: FileMinus,
    color: "blue",
    config: { mode: "delete-pages", accept: ".pdf" },
  },
  {
    id: "unlock-pdf",
    type: "pdf",
    title: "Unlock PDF",
    desc: "Remove the password from a PDF you can already open, for easy uploads.",
    leadIn: "Remove the password from a PDF you can already open — the kind banks put on statements (often your PAN plus date of birth) that portals then reject for KYC or loan uploads. This is not a cracker: you enter the password you already know and get back a clean, openable copy. Your statement is processed in your browser, never uploaded.",
    icon: Unlock,
    color: "blue",
    config: { mode: "unlock", accept: ".pdf" },
  },
  {
    id: "ocr-pdf",
    type: "pdf",
    title: "OCR PDF",
    desc: "Read text off a scanned PDF, in English or Hindi.",
    leadIn: "Turn a scanned PDF back into text you can actually select, search and paste. Photographed pages, a scanner copy, an old certificate — the tool reads the words straight off the page images, in English, Hindi, or both together for the bilingual forms most Indian paperwork uses. It runs inside your browser, so the document never leaves your device.",
    icon: ScanText,
    color: "blue",
    config: { mode: "ocr-pdf", accept: ".pdf" },
  },
  {
    id: "pdf-to-text",
    type: "pdf",
    title: "PDF to Text",
    desc: "Extract all selectable text from a PDF into plain text.",
    leadIn: "Pull the words out of a PDF as clean, copyable plain text — a few paragraphs for an email, the questions from a paper, a clause from an agreement, without retyping. Copy it with one tap or download it as a .txt file. It reads the PDF right in your browser, so nothing is uploaded.",
    icon: Type,
    color: "blue",
    config: { mode: "pdf-to-text", accept: ".pdf" },
  },
  {
    id: "organize-pdf",
    type: "pdf",
    title: "Organize PDF",
    desc: "Reorder, rotate, and delete PDF pages on one screen.",
    leadIn: "Reorder, rotate, and delete PDF pages on a single screen instead of running the file through three separate tools. See every page as a thumbnail, drag them into order, turn the sideways ones upright, and drop the blank or unwanted ones — then export one clean PDF. Rotations stay with their page, and nothing is uploaded.",
    icon: LayoutGrid,
    color: "orange",
    config: { mode: "organize", accept: ".pdf" },
  },

  {
    id: "sign-pdf",
    type: "pdf",
    title: "Sign PDF",
    desc: "Draw, type, or upload a signature and place it on your PDF.",
    icon: PenTool,
    color: "orange",
    config: { mode: "sign", accept: ".pdf" },
  },

  {
    id: "remove-pdf-metadata",
    type: "pdf",
    title: "Remove PDF Metadata",
    desc: "See and strip the hidden title, author and software details in a PDF.",
    leadIn: "Every PDF quietly carries a title, an author name, and the name of the software that made it \u2014 often your real name, or your employer's licence. See exactly what your file is carrying, edit any of it, or strip it out completely. The file is read and rewritten inside your browser, so it never leaves your device.",
    icon: FileSearch,
    color: "orange",
    config: { mode: "metadata", accept: ".pdf" },
  },

  // ==========================================
  // IMAGE TOOLS
  // ==========================================
  {
    id: "compress-jpg",
    type: "image",
    title: "Compress JPG",
    desc: "Reduce JPG size without quality loss.",
    leadIn: "Reduce a JPG's file size for uploads, email, or a faster website — with a live before/after preview so you judge the quality before downloading. Drag the slider for a quick trade-off, or set a target size when a form caps you at a specific KB. The photo is processed right in your browser.",
    icon: Minimize2,
    color: "blue",
    config: { showQuality: true, defaultQuality: 0.8, defaultFormat: "image/jpeg", lockFormat: true, allowBatch: true, accept: ".jpg,.jpeg,image/jpeg" },
  },
  {
    id: "compress-jpeg",
    type: "image",
    title: "Compress JPEG",
    desc: "Reduce JPEG size efficiently.",
    leadIn: "Shrink a heavy JPEG for an upload, an email, or a website — including down to a strict 20 KB, 50 KB, or 100 KB when a form demands it. A quality slider lets you trade size against sharpness with a live preview, and you can process a batch at once. The photo is compressed on your device, never uploaded.",
    icon: Minimize2,
    color: "blue",
    config: { showQuality: true, defaultQuality: 0.8, defaultFormat: "image/jpeg", lockFormat: true, allowBatch: true, accept: ".jpg,.jpeg,image/jpeg" },
  },
  {
    id: "compress-webp",
    type: "image",
    title: "Compress WebP",
    desc: "Reduce WebP file size.",
    leadIn: "Squeeze a WebP image down for a faster-loading website without wrecking its quality — the kilobytes that Core Web Vitals and PageSpeed actually count. Transparency is preserved, and you can optimise a batch of assets in one go. Compression runs in your browser, so nothing is uploaded to a server.",
    icon: Minimize2,
    color: "blue",
    config: { showQuality: true, defaultQuality: 0.8, defaultFormat: "image/webp", lockFormat: true, allowBatch: true, accept: ".webp,image/webp" },
  },
  {
    id: "compress-png",
    type: "image",
    title: "Compress PNG",
    desc: "Reduce PNG file size while keeping transparency.",
    leadIn: "Actually shrink a PNG — not just re-save it. PNG is lossless, so basic tools barely change the size; this one quantises the colours to cut the file properly while keeping sharp edges and transparent backgrounds intact. Use Target size mode to hit a specific KB, all processed on your own device.",
    icon: Minimize2,
    color: "blue",
    config: { showQuality: true, defaultQuality: 0.8, defaultFormat: "image/png", lockFormat: true, allowBatch: true, accept: ".png,image/png" },
  },
  {
    id: "resize",
    type: "image",
    title: "Resize Image",
    desc: "Change image dimensions and resolution.",
    leadIn: "Resize an image to exact pixel dimensions — a 400×400 profile picture, a 200×230 passport photo, or any custom width and height. Lock the aspect ratio to avoid stretching, or tap a preset for common sizes. Everything runs on your own device, with no watermark and nothing uploaded.",
    icon: Maximize2,
    color: "blue",
    config: { showResize: true, showFormat: true, defaultQuality: 0.9, allowBatch: false },
  },
  {
    id: "combine-images",
    type: "image",
    title: "Combine Images",
    desc: "Join two or more photos into one image.",
    leadIn: "Place your photos on a blank A4 page and arrange them by hand \u2014 the front and back of an Aadhaar or PAN card, both sides of a cheque, or two screenshots. Drag each photo anywhere on the page and resize it from the corner, choose portrait or landscape, and download one JPG or PNG. Nothing is uploaded; the page is built on your own device.",
    icon: Combine,
    color: "purple",
    config: { mode: "combine", allowBatch: true, accept: ".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" },
  },
  {
    id: "crop",
    type: "image",
    title: "Crop Image",
    desc: "Trim unwanted outer areas from photos.",
    leadIn: "Crop a photo down to just what matters — cut out a photobomber, trim empty sky, or remove clutter from a product shot. Drag the visual selector to re-frame the image and download the tighter version. No Photoshop, no upload — the crop happens right in your browser.",
    icon: CropIcon,
    color: "blue",
    config: { showVisualCrop: true, allowBatch: false },
  },
  {
    id: "convert-webp",
    type: "image",
    title: "Convert to WebP",
    desc: "Convert images to the modern WebP format.",
    leadIn: "Convert JPG, PNG, or JPEG images into WebP — Google's modern format that is typically 25–35% smaller at the same quality, so pages load faster. Transparency is carried over, and you can convert a whole batch at once. Everything runs on your device, with nothing uploaded.",
    icon: RefreshCw,
    color: "blue",
    config: { showFormat: true, defaultFormat: "image/webp", lockFormat: true, allowBatch: true, accept: ".jpg,.jpeg,.png,.gif,.bmp,image/jpeg,image/png,image/gif,image/bmp" },
  },
  {
    id: "convert-jpg",
    type: "image",
    title: "Convert to JPG",
    desc: "Convert PNG, WebP, and others to JPG.",
    leadIn: "Convert almost any image — PNG, WebP, HEIC, TIFF, BMP — into JPG, the format every portal and old device accepts. Transparent areas are filled cleanly instead of turning black, and the result is much smaller than a PNG. Convert one image or a batch, all inside your browser.",
    icon: RefreshCw,
    color: "blue",
    config: { showFormat: true, defaultFormat: "image/jpeg", lockFormat: true, allowBatch: true, accept: ".png,.webp,.gif,.bmp,image/png,image/webp,image/gif,image/bmp" },
  },
  {
    id: "convert-png",
    type: "image",
    title: "Convert to PNG",
    desc: "Convert JPG and WebP to PNG format.",
    leadIn: "Convert a JPG or WebP into PNG when quality matters more than size — a logo, a screenshot, a graphic with sharp text or lines. PNG is lossless, so every pixel is preserved with no compression blur, and transparency is kept. Convert one image or a batch, processed entirely on your device.",
    icon: RefreshCw,
    color: "blue",
    config: { showFormat: true, defaultFormat: "image/png", lockFormat: true, allowBatch: true, accept: ".jpg,.jpeg,.webp,.gif,.bmp,image/jpeg,image/webp,image/gif,image/bmp" },
  },
  {
    id: "heic-to-jpg",
    type: "image",
    title: "HEIC to JPG",
    desc: "Convert iPhone HEIC photos to JPG, PNG, or WebP.",
    leadIn: "Convert iPhone HEIC photos into JPG so they actually open everywhere — job portals, college forms, Windows, websites that reject HEIC. Pick JPG for universal compatibility, or PNG/WebP if you prefer, and convert a whole batch at once. Your photos are decoded on your device and never leave your browser.",
    icon: ImageDown,
    color: "blue",
    config: {
      showFormat: true,
      defaultFormat: "image/jpeg",
      defaultQuality: 0.9,
      allowBatch: true,
      accept: ".heic,.heif,image/heic,image/heif"
    },
  },
  {
    id: "heic-to-png",
    type: "image",
    title: "HEIC to PNG",
    desc: "Convert iPhone HEIC photos to lossless PNG.",
    leadIn: "Convert iPhone HEIC photos into lossless PNG — the right choice when you plan to edit the image afterwards. Unlike JPG, PNG throws away nothing, so you keep a pixel-perfect copy with no compression blur, ready to retouch or drop into a design. The conversion runs in your browser, so nothing is uploaded.",
    icon: ImageDown,
    color: "blue",
    config: {
      showFormat: true,
      defaultFormat: "image/png",
      defaultQuality: 0.92,
      allowBatch: true,
      accept: ".heic,.heif,image/heic,image/heif"
    },
  },
  {
    id: "heic-to-webp",
    type: "image",
    title: "HEIC to WebP",
    desc: "Convert iPhone HEIC photos to lightweight WebP for the web.",
    leadIn: "Convert iPhone HEIC photos into WebP when they are headed for a website — a blog, a store, a portfolio. WebP looks as good as JPG or PNG while weighing noticeably less, so pages load faster and rank better. Transparency is supported, and the whole conversion happens on your device.",
    icon: ImageDown,
    color: "blue",
    config: {
      showFormat: true,
      defaultFormat: "image/webp",
      defaultQuality: 0.85,
      allowBatch: true,
      accept: ".heic,.heif,image/heic,image/heif"
    },
  },
  {
    id: "rotate",
    type: "image",
    title: "Rotate Image",
    desc: "Rotate images 90, 180, or 270 degrees.",
    leadIn: "Rotate a sideways or upside-down photo and have the fix saved into the file itself — not just turned on screen, which reverts the moment you upload or email it. Turn JPG, PNG, or WebP images by 90, 180, or 270 degrees. Everything happens instantly in your browser, with nothing uploaded.",
    icon: RotateCw,
    color: "blue",
    config: { showRotate: true, showFormat: true, allowBatch: false },
  },
  {
    id: "flip",
    type: "image",
    title: "Flip Image",
    desc: "Mirror images horizontally or vertically.",
    leadIn: "Mirror an image horizontally to fix a selfie where the text reads backwards, or vertically for a creative effect. A live preview shows the result as you flip, and it works on JPG, PNG, and WebP. The whole thing runs in your browser — no upload, no watermark.",
    icon: FlipHorizontal,
    color: "blue",
    config: { showFlip: true, showFormat: true, allowBatch: false },
  },
  {
    id: "color-picker",
    type: "image",
    title: "Color Picker",
    desc: "Extract Hex and RGB colors from images.",
    leadIn: "Find the exact colour in any image — that precise shade of blue in a logo, a sunset, or a website design. Upload a picture, hover with the magnifier for pixel-level accuracy, and read the colour back as a Hex code or RGB values to drop straight into your design. No software, and the image never leaves your browser.",
    icon: Palette,
    color: "blue",
    config: { mode: "picker", allowBatch: false },
  },
  {
    id: "aadhaar-masking",
    type: "image",
    title: "Aadhaar & ID Masking",
    desc: "Securely redact sensitive identity information.",
    leadIn: "Black out the sensitive parts of an ID before you share a copy — the first 8 digits of an Aadhaar number, a photo, or any detail you do not want exposed for a hotel check-in or SIM form. You draw boxes over what to hide, and the tool flattens them into the image so the covered data is genuinely gone, not just hidden. All of it happens on your device.",
    icon: ShieldAlert,
    color: "blue",
    config: { mode: "mask", showVisualCrop: false, showMaskTool: true, allowBatch: false },
  },
  {
    id: "qr-generator",
    type: "utility",
    title: "QR Generator",
    desc: "Create custom QR codes for URLs and text.",
    leadIn: "Create a free QR code for a link, some text, or your Wi-Fi details — the kind people scan straight off a screen or a printout. These are static codes, so the data lives in the QR itself and never expires behind a subscription. Choose the size and error-correction level, and generate it instantly in your browser.",
    icon: QrCode,
    color: "purple",
    config: { mode: "qr" },
  }
];